# Netlist Viewer TCL File
set_family -name PolarFireSoC
top_module -name MPFS_ICICLE_KIT_BASE_DESIGN
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/CLK_DIV/CLK_DIV_0/CLK_DIV_CLK_DIV_0_PF_CLK_DIV.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/CLK_DIV/CLK_DIV.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/CORERESET/CORERESET_0/core/corereset_pf.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/CORERESET/CORERESET.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/GLITCHLESS_MUX/GLITCHLESS_MUX_0/GLITCHLESS_MUX_GLITCHLESS_MUX_0_PF_NGMUX.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/GLITCHLESS_MUX/GLITCHLESS_MUX.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/INIT_MONITOR/INIT_MONITOR_0/INIT_MONITOR_INIT_MONITOR_0_PFSOC_INIT_MONITOR.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/INIT_MONITOR/INIT_MONITOR.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/OSCILLATOR_160MHz/OSCILLATOR_160MHz_0/OSCILLATOR_160MHz_OSCILLATOR_160MHz_0_PF_OSC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/OSCILLATOR_160MHz/OSCILLATOR_160MHz.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/PCIE_REF_CLK/PCIE_REF_CLK_0/PCIE_REF_CLK_PCIE_REF_CLK_0_PF_XCVR_REF_CLK.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/PCIE_REF_CLK/PCIE_REF_CLK.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/PF_CCC_C0/PF_CCC_C0_0/PF_CCC_C0_PF_CCC_C0_0_PF_CCC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/PF_CCC_C0/PF_CCC_C0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/TRANSMIT_PLL/TRANSMIT_PLL_0/TRANSMIT_PLL_TRANSMIT_PLL_0_PF_TX_PLL.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/TRANSMIT_PLL/TRANSMIT_PLL.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/CLOCKS_AND_RESETS/CLOCKS_AND_RESETS.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/ResetSycnc.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/MasterAddressDecoder.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/DependenceChecker.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/BitScan0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/TransactionController.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/MasterControl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RoundRobinArb.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/TargetMuxController.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/AddressController.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/Revision.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/DERR_Slave.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/DualPort_FF_SyncWr_SyncRd.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/DualPort_Ram_SyncWr_SyncRd.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RdFifoDualPort.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/ReadDataMux.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RequestQual.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/ReadDataController.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RDataController.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/SlaveDataMuxController.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RespController.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/FifoDualPort.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/WriteDataMux.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/WDataController.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/Axi4CrossBar.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/AHBL_Ctrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/AXI4_Read_Ctrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/AXI4_Write_Ctrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/AHB_SM.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MstrAHBtoAXI4Converter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/Bin2Gray.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/CDC_grayCodeCounter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/CDC_rdCtrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/CDC_wrCtrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/RAM_BLOCK.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/CDC_FIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MstrClockDomainCrossing.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_CmdFifoWriteCtrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/Hold_Reg_Ctrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_Hold_Reg_Rd.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_preCalcCmdFifoWrCtrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_widthConvrd.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/FIFO_CTRL.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/FIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/byte2bit.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_readWidthConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_Hold_Reg_Wr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_widthConvwr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_brespCtrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_writeWidthConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DownConverter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_AChannel.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_BChannel.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_RChannel_SlvRid_Arb.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_RChan_Ctrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_preCalcRChan_Ctrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/FIFO_downsizing.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_RChannel.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_WChan_Hold_Reg.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_WChan_ReadDataFifoCtrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_Wchan_WriteDataFifoCtrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/FIFO_upsizing.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_WChannel.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_preCalcAChannel.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/UpConverter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MstrDataWidthConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MstrProtocolConverter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/RegSliceFull.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/RegisterSlice.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MasterConvertor.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvClockDomainCrossing.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvDataWidthConverter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvAxi4ProtConvRead.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvAxi4ProtConvWrite.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvAxi4ProtocolConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvAxi4ProtConvAXI4ID.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvProtocolConverter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlaveConvertor.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/CoreAxi4Interconnect.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC0_INITIATOR/FIC0_INITIATOR.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/address_generator.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/conflict_free_memory_map.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/delay.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/fsm.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {F:\MPFS_Projects\MPFS_ICICLE\hdl}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/add_sub_rd.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {F:\MPFS_Projects\MPFS_ICICLE\hdl}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/mult_rd.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/poly_mul.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/arbiter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/network_bank_in.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/network_bf_in.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/network_bf_out.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/poly_bank.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/poly_ram.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/polyvec_ram.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/tf_ROM.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/tf_address_generator.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {F:\MPFS_Projects\MPFS_ICICLE\hdl}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/poly_ntt.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC_0_PERIPHERALS/FIC_0_PERIPHERALS.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/AXI4_address_shim.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC_1_INITIATOR/FIC_1_INITIATOR.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/PCIE_INITIATOR/PCIE_INITIATOR.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/SgCore/PF_PCIE/2.0.116/g5_apblink_master.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/PF_PCIE_C0/PF_PCIE_C0_0/PF_PCIE_C0_PF_PCIE_C0_0_PF_PCIE.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/PF_PCIE_C0/PF_PCIE_C0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC_1_PERIPHERALS/FIC_1_PERIPHERALS.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/apb_arbiter.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/APB_PASS_THROUGH.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3_muxptob3.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3_iaddr_reg.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC_3_0x4000_0xxx/FIC_3_0x4000_0xxx.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC_3_0x4FFF_Fxxx/FIC_3_0x4FFF_Fxxx.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC_3_0x4xxx_xxxx/FIC_3_0x4xxx_xxxx.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC_3_ADDRESS_GENERATION/FIC_3_ADDRESS_GENERATION.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/GPIO/GPIO_0/rtl/vlog/core/coregpio.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/GPIO/GPIO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/IHC_APB/IHC_APB.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/miv_ihcia.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/miv_ihcc_mem.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/miv_ihcc_irqs.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/miv_ihcc_ctrl.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/miv_ihcc.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/IHC_SUBSYSTEM/IHC_SUBSYSTEM.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/RECONFIGURATION_INTERFACE/RECONFIGURATION_INTERFACE_0/RECONFIGURATION_INTERFACE_RECONFIGURATION_INTERFACE_0_PF_DRI.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/RECONFIGURATION_INTERFACE/RECONFIGURATION_INTERFACE.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/hdl/fabric_sd_emmc_demux_select.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/FIC_3_PERIPHERALS/FIC_3_PERIPHERALS.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/ICICLE_MSS/MSS_NOBYP_NOBYP_NOBYP_BYP_BYP_syn_comps.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/ICICLE_MSS/ICICLE_MSS.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/MSS_WRAPPER/MSS_WRAPPER.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/component/work/MPFS_ICICLE_KIT_BASE_DESIGN/MPFS_ICICLE_KIT_BASE_DESIGN.v}
addfile -view HIER -lib work -type VLOG -mode system_verilog -name {F:/MPFS_Projects/MPFS_ICICLE/synthesis/MPFS_ICICLE_KIT_BASE_DESIGN.vm}
addfile -view FLAT -lib work -type AFL -mode NONE -name {F:/MPFS_Projects/MPFS_ICICLE/designer/MPFS_ICICLE_KIT_BASE_DESIGN/MPFS_ICICLE_KIT_BASE_DESIGN.afl}